<script src="<?= BASE_URL ?>Dependencies/bootstrap-5.2.3-dist/js/bootstrap.bundle.min.js"></script>

<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="fixed-bottom">

    <section class="">
        <!-- Footer -->
        <footer class="text-center text-white" style="background-color: #0a4275;">
            <!-- Grid container -->
            <div class="container p-3 pb-0">
                <!-- Section: CTA -->
                <section class="">
                    <p class="d-flex justify-content-center align-items-center">
                        <span class="me-3">Footer</span>
                        <!-- <button type="button" class="btn btn-outline-light btn-rounded">
                            Sign up!
                        </button> -->
                    </p>
                </section>
                <!-- Section: CTA -->
            </div>
            <!-- Grid container -->

            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                © 2020 
                <a class="text-white" href="#">Core MVC</a>
            </div>
            <!-- Copyright -->
        </footer>
        <!-- Footer -->
    </section>

</div>
<!-- End of .container -->

</body>

</html>